### ISSUE TITLE
Custom component integration error

### ISSUE THREAD

**Issue by sacredx72** [deblockt/hass-proscenic-790T-vacuum#13]
Good evening, I found your integration, and I was very glad that my old vacuum cleaner can work with HA / But I am having problems integrating your custom component into HA. installed manually and via HACS. The result is one, the integration does not want to load into HA.
`Logger: aiohttp.server
Source: components/hassio/__init__.py:518
First occurred: 21:38:25 (3 occurrences)
Last logged: 21:42:52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 376, in post
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error vacuum.proscenic - Integration 'proscenic' not found.`
 Настройка configuration.yaml
`##Prosceniv vacum
vacuum:
  - platform: proscenic
    host: 192.168.1.**
    deviceId: 4555b85******
    token: FAHby59*****G7******25171
    authCode: 1010***20
    userId: 02fa6fd*********2b5292be3c08
    name: T790
    sleep_duration_on_exit: 30# default 60. number of second waiting before reconnection (if you use proscenic app)`

**Comment by deblockt** [comment]
Hi, 

I performed a fresh install of hass, and I have the same issue, I will take a look to update the integration.

**Comment by deblockt** [comment]
@sacredx72 The issue has been fixed on version 0.0.6
