### ISSUE TITLE
The proscenic custom integration is using deprecated vacuum feature

### ISSUE THREAD

**Issue by paulrafu** [deblockt/hass-proscenic-790T-vacuum#31]
The custom integration proscenic is extending the deprecated base class VacuumEntity instead of StateVacuumEntity.
This stops working in version 2024.2.0. Please address before upgrading.
Please report it to the author of the proscenic custom integration...

**Comment by deblockt** [comment]
Hi, Can you try with the code on available here https://github.com/deblockt/hass-proscenic-790T-vacuum/tree/fix/vacuumentity ? 
I can not test on my side since I have sold my proscenic vaccum.

**Comment by paulrafu** [comment]
I will try it when I get home.

**Comment by paulrafu** [comment]
Hi,
Thank's for your work!
I uninstal old version and installed your code.
I added integration and i tried booth type of connection local and cloud.
Robot don't start...
Here is log:

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:851
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:36:23 PM (4 occurrences)
Last logged: 9:45:20 PM

[548146028608] Entity vacuum.060c750d12933bdc does not support this service.
[547584590528] Entity vacuum.060c750d12933bdc does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity vacuum.060c750d12933bdc does not support this service.

**Comment by terslowe** [comment]
Any news about the solution? I get also the same error.

**Comment by Foltifeki** [comment]
Hello, I have the same problem, I tried to rewrite the code with ai, I got so far that the integration loads but it only says: "The configuration process cannot be loaded: 500 Internal Server Error Server got itself in trouble"

I don't understand this at all, I just rewrote all the files as ai said
it would be nice if there was a solution for it
